//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class MsgTipStruct
{
	public MsgTipStruct ()
	{
	}

	public string content = "";

	public int showCount = 0;

	public Vector3 TextPos = Vector3.zero;
	public Color TextColor = new Color(1,1,1);
}

